import {useState} from 'react';
import Link from '@/lib/link';
import {authService} from '@/services';
import {errorMessage} from '@/services/client';
export default function ResetPassword(){
 const [token]=useState(()=>{const params=new URLSearchParams(window.location.hash.slice(1));const value=params.get('type')==='recovery'?params.get('access_token')||'':'';if(window.location.hash)window.history.replaceState(null,'',window.location.pathname);return value;});
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[repeat,setRepeat]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[done,setDone]=useState(false);
 return <main className="page-container" id="main"><Link href="/admin/login" className="text-link">Back to login</Link><form className="settings-form panel" onSubmit={async e=>{e.preventDefault();setError('');setMessage('');if(token&&password!==repeat){setError('The passwords do not match.');return;}setBusy(true);try{if(token){await authService.changePassword(token,password);setDone(true);setPassword('');setRepeat('');setMessage('Password updated. You can now sign in.');}else{const result=await authService.resetPassword(email) as {message:string};setMessage(result.message);}}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}><h1>{token?'Choose a new password':'Reset your password'}</h1>{!done&&(token?<><label className="field"><span>New password (at least 12 characters)</span><input type="password" autoComplete="new-password" minLength={12} maxLength={128} required value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="field"><span>Confirm password</span><input type="password" autoComplete="new-password" minLength={12} maxLength={128} required value={repeat} onChange={e=>setRepeat(e.target.value)}/></label></>:<label className="field"><span>Admin email</span><input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label>)}{error&&<p className="form-error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{!done&&<button className="button primary" disabled={busy}>{busy?'Please wait…':token?'Update password':'Send reset link'}</button>}</form></main>;
}
