import {useState,useEffect} from 'react';import Link from '@/lib/link';import {ArrowUpRight,ArrowRight,Sparkles,Music2,Palette,Mic2,Theater,ChevronLeft,ChevronRight} from 'lucide-react';
import {Pagination,PaginationContent,PaginationItem} from '@/components/ui/pagination';
import {houseService,programCategoryService,eventService,resultService,galleryService,scoreService} from '@/services';import {useResource,useDebounced} from '@/services/hooks';
import {Navbar,Footer,Heading,PageHeading,TextLink,State,LiveBadge,FieldSelect,SearchBox,FilterPills} from './ui';import {Standings,StandingsRotator,ScoreChart,PointsBreakdown,EventCards,LatestResultRotator,ResultTable,GalleryGrid,CertificateButton} from './data-views';
import type {Result} from '@/services/models';

function Hero(){return <><section className="hero"><img className="hero-image" src="/festival-hero.webp" fetchPriority="high" alt="Original festival artwork of a classical dancer under amber stage lights"/><div className="hero-shade"/><div className="hero-content"><div className="hero-presenter"><p className="hero-presenter-copy">GHS BEENACHI<br/>LITTLE KITES PRESENTS</p><span className="hero-presenter-logo"><img src="/little-kites-logo.png" alt="Little Kites logo" width="100" height="79"/></span></div><h1>A stage for<br/>every <em>spark.</em></h1><p className="hero-program">YEBETH<span>2k26</span> <span className="hero-separator">/</span> ARTS FESTIVAL 2026</p><p className="hero-description">Where creativity meets competition.<br/>And every talent finds its moment.</p><div className="hero-actions"><Link className="button primary" href="/scores">View live scores <ArrowUpRight size={19}/></Link><Link className="button glass" href="/gallery">Explore gallery <ArrowRight size={18}/></Link></div></div><div className="hero-foot"><span><Sparkles size={17}/> ART. TALENT. TOGETHER.</span><span>THE GHS BEENCHI ARTS FESTIVAL <span className="edition">2026 EDITION</span></span></div><span className="image-credit">Festival artwork</span></section><div className="festival-ribbon"><span>MAKE YOUR MARK.</span><Sparkles/><span>FIND YOUR VOICE.</span><Sparkles/><span>OWN THE STAGE.</span><Sparkles/><span>CELEBRATE THE ARTS.</span></div></>;}
async function loadAllHomeResults(signal:AbortSignal){let cursor:string|undefined;const items:Result[]=[];do{const page=await resultService.list({limit:200,sort:'-date',...(cursor?{cursor}:{})},signal);items.push(...page.items);cursor=page.nextCursor||undefined}while(cursor);return {items,total:items.length,nextCursor:null};}
function Home(){const houses=useResource('houses',s=>houseService.all(s));const results=useResource('results:latest',loadAllHomeResults);const events=useResource('events:home',s=>eventService.list({limit:3,sort:'date'},s));const gallery=useResource('gallery:home',s=>galleryService.list({limit:6,sort:'-createdAt'},s));return <><Hero/><section className="section"><Heading kicker="LIVE HOUSE STANDINGS" title="Every point. Every house." action={<TextLink href="/scores">Full leaderboard</TextLink>}/><LiveBadge {...houses}/>{houses.data?.some(h=>h.enabled)?<><StandingsRotator houses={houses.data}/><ScoreChart houses={houses.data}/></>:<State kind="scores" {...houses} onRetry={houses.refresh}/>}</section><section className="section section-tinted"><Heading kicker="LATEST RESULTS" title="Talent, recognised." action={<TextLink href="/results">View all results</TextLink>}/>{results.data?.items.length?<LatestResultRotator results={results.data.items} houses={houses.data||[]}/>:<State kind="results" {...results} onRetry={results.refresh}/>}</section><section className="section"><Heading kicker="THE PROGRAMME" title="Find your kind of art." action={<TextLink href="/events">Explore all events</TextLink>}/>{events.data?.items.length?<EventCards events={events.data.items}/>:<State kind="events" {...events} onRetry={events.refresh}/>}</section><section className="gallery-section section"><Heading kicker="EVENT HIGHLIGHTS" title="Some moments stay with you." action={<TextLink href="/gallery">View full gallery</TextLink>}/>{gallery.data?.items.length?<GalleryGrid images={gallery.data.items}/>:<State kind="gallery" {...gallery} onRetry={gallery.refresh}/>}</section><section className="about-banner"><p className="eyebrow">THE SPIRIT OF YEBETH2k26</p><h2>Many talents.<br/><em>One unforgettable celebration.</em></h2><div><p>From the first brushstroke to the final bow, a celebration of the voices, ideas and imagination of GHS BEENCHI.</p><TextLink href="/about">Meet the festival</TextLink></div></section></>;}
function Scores(){const houses=useResource('houses',s=>houseService.all(s));const breakdown=useResource('breakdown',s=>scoreService.breakdown(s));const active=(houses.data||[]).filter(h=>h.enabled).sort((a,b)=>b.points-a.points);const leaders=active.filter(h=>h.points===active[0]?.points);return <div className="page-container"><PageHeading kicker="THE LEADERBOARD" title="Live house standings." description="Every performance counts. Follow the race, point by point."><LiveBadge {...houses}/></PageHeading>{active.length?<><div className="current-leader"><span className="eyebrow">{leaders.length>1?'JOINT LEADERS':'CURRENT LEADER'}</span><h2>{leaders.map(h=>h.name).join(' & ')}</h2><strong>{active[0].points.toLocaleString()} <small>POINTS</small></strong></div><Standings houses={active}/><ScoreChart houses={active}/></>:<State kind="scores" {...houses} onRetry={houses.refresh}/>}<section className="inner-section"><Heading kicker="BEHIND THE NUMBERS" title="Points breakdown" description="See how each house earned its points across the arts."/>{breakdown.data?.length?<PointsBreakdown houses={active} items={breakdown.data}/>:<State kind="scores" {...breakdown} onRetry={breakdown.refresh} title="Every performance has a part to play." description="Points by category will appear once results are published."/>}</section></div>;}
export function Pager({next,total,history,onNext,onBack}:{next?:string|null;total?:number;history:string[];onNext:()=>void;onBack:()=>void}){return <div className="pager"><span>{total===undefined?'No entries yet':`${total} ${total===1?'entry':'entries'}`}</span><Pagination><PaginationContent><PaginationItem><button className="icon-button" aria-label="Previous page" disabled={!history.length} onClick={onBack}><ChevronLeft size={19}/></button></PaginationItem><PaginationItem><span>Page {history.length+1}</span></PaginationItem><PaginationItem><button className="icon-button" aria-label="Next page" disabled={!next} onClick={onNext}><ChevronRight size={19}/></button></PaginationItem></PaginationContent></Pagination></div>;}
export function usePaging(resetKey:string){const [cursor,setCursor]=useState('');const [history,setHistory]=useState<string[]>([]);useEffect(()=>{setCursor('');setHistory([])},[resetKey]);return {cursor,history,next:(next:string)=>{setHistory(v=>[...v,cursor]);setCursor(next)},back:()=>{setCursor(history[history.length-1]||'');setHistory(v=>v.slice(0,-1))}};}
function Events(){const [category,setCategory]=useState('All');const [status,setStatus]=useState('all');const [search,setSearch]=useState('');const debounced=useDebounced(search);const categories=useResource('program-categories',s=>programCategoryService.all(s));const filter=JSON.stringify({category,status,debounced});const paging=usePaging(filter);const query={programCategory:category==='All'?undefined:category,status:status==='all'?undefined:status,search:debounced,cursor:paging.cursor,limit:12,sort:'date'};const events=useResource('events:'+JSON.stringify(query),s=>eventService.list(query,s));const rankings=useResource('program-rankings:'+category,s=>scoreService.programRankings({programCategory:category==='All'?undefined:category},s));return <div className="page-container"><PageHeading kicker="THE PROGRAMME" title="Find your stage." description="Browse every programme by participation category, schedule and result status."/><div className="filter-toolbar"><SearchBox value={search} onChange={setSearch} label="Search programmes"/><FieldSelect label="Programme status" value={status} onChange={setStatus} options={['all','upcoming','live','completed'].map(value=>({value,label:value==='all'?'All statuses':value.charAt(0).toUpperCase()+value.slice(1)}))}/></div><FilterPills value={category} onChange={setCategory} values={(categories.data||[]).map(c=>c.name)}/>{events.data?.items.length?<EventCards events={events.data.items} rankings={rankings.data||[]}/>:<State kind="events" {...events} onRetry={events.refresh} title={category!=='All'||search||status!=='all'?'No programmes match these filters.':undefined} description={category!=='All'||search||status!=='all'?'Try another category, search or status.':undefined}/>}<Pager next={events.data?.nextCursor} total={events.data?.total} history={paging.history} onNext={()=>events.data?.nextCursor&&paging.next(events.data.nextCursor)} onBack={paging.back}/></div>;}
function Results(){
 const [event,setEvent]=useState('all');
 const [category,setCategory]=useState('all');
 const [house,setHouse]=useState('all');
 const [search,setSearch]=useState('');
 const [sort,setSort]=useState('-date');
 const debounced=useDebounced(search);
 const filter=JSON.stringify({event,category,house,debounced,sort});
 const paging=usePaging(filter);
 const houses=useResource('houses',s=>houseService.all(s));
 const events=useResource('events:options',s=>eventService.list({limit:200,sort:'name'},s));
 const categoryOptions=['HS','LP','UP'];
 const query={eventId:event==='all'?undefined:event,category:category==='all'?undefined:category,houseId:house==='all'?undefined:house,search:debounced,sort,cursor:paging.cursor,limit:20};
 const results=useResource('results:'+JSON.stringify(query),s=>resultService.list(query,s));
 const filtered=event!=='all'||category!=='all'||house!=='all'||!!search;
 const reset=()=>{setEvent('all');setCategory('all');setHouse('all');setSearch('');setSort('-date')};
 return <div className="page-container results-page"><PageHeading kicker="THE ACHIEVEMENTS" title="Every win, celebrated." description="Official event results from YEBETH2k26. Find your result and download a beautiful certificate to keep."/><div className="filter-toolbar result-filters"><FieldSelect label="Event" value={event} onChange={setEvent} options={[{value:'all',label:'All events'},...(events.data?.items||[]).map(e=>({value:e.id,label:e.name}))]}/><FieldSelect label="Category" value={category} onChange={setCategory} options={[{value:'all',label:'All categories'},...categoryOptions.map(value=>({value,label:value}))]}/><FieldSelect label="House" value={house} onChange={setHouse} options={[{value:'all',label:'All houses'},...(houses.data||[]).map(h=>({value:h.id,label:h.name}))]}/><button className="text-reset" onClick={reset}>Reset filters</button></div><div className="filter-toolbar"><SearchBox value={search} onChange={setSearch} label="Search results"/><FieldSelect label="Sort results" value={sort} onChange={setSort} options={[{value:'-date',label:'Newest first'},{value:'date',label:'Oldest first'},{value:'position',label:'Position'},{value:'-points',label:'Most points'}]}/></div>{results.data?.items.length?<ResultTable results={results.data.items} houses={houses.data||[]} actions={result=><CertificateButton result={result} house={houses.data?.find(item=>item.id===result.houseId)}/>} />:<State kind="results" {...results} onRetry={results.refresh} title={filtered?'No results match these filters.':undefined}/>}<Pager next={results.data?.nextCursor} total={results.data?.total} history={paging.history} onNext={()=>results.data?.nextCursor&&paging.next(results.data.nextCursor)} onBack={paging.back}/></div>;
}
function Gallery(){const [category,setCategory]=useState('All');const paging=usePaging(category);const query={category:category==='All'?undefined:category,cursor:paging.cursor,limit:24,sort:'-createdAt'};const gallery=useResource('gallery:'+JSON.stringify(query),s=>galleryService.list(query,s));return <div className="page-container"><PageHeading kicker="EVENT GALLERY" title="The moments. The magic." description="Moments from the festival. A little of the energy, saved forever."/><FilterPills value={category} onChange={setCategory} values={['Dance','Music','Drama','Painting','Literary','Ceremony','Other']}/>{gallery.data?.items.length?<GalleryGrid images={gallery.data.items}/>:<State kind="gallery" {...gallery} onRetry={gallery.refresh} title={category!=='All'?'No moments in this category yet.':undefined}/>}<Pager next={gallery.data?.nextCursor} total={gallery.data?.total} history={paging.history} onNext={()=>gallery.data?.nextCursor&&paging.next(gallery.data.nextCursor)} onBack={paging.back}/></div>;}
function About(){return <div className="page-container about-page"><PageHeading kicker="GHS BEENCHI · ARTS FESTIVAL 2026" title="A little courage. A lot of creativity." description="This is YEBETH2k26. A place for expression, friendly competition and the joy of creating together."/><div className="about-story"><div className="about-image"><img src="/festival-hero.webp" alt="Classical dance festival artwork" loading="lazy"/><span>FESTIVAL ARTWORK</span></div><div><p className="eyebrow ink">THE SPIRIT OF OUR FESTIVAL</p><h2>Every talent deserves<br/>a moment in the light.</h2><p>YEBETH2k26 is the school arts festival of GHS BEENCHI, bringing students together through performance, visual art and the written word.</p><p>It is a celebration of practice and possibility. Of showing up for your house, cheering for a friend, and finding the confidence to share something of your own.</p><TextLink href="/events">Explore the programme</TextLink></div></div><div className="art-disciplines">{[[Music2,'Find your rhythm','Music & performance'],[Palette,'Make your mark','Visual arts'],[Theater,'Tell your story','Dance & drama'],[Mic2,'Let words take flight','Literary arts']].map(([Icon,title,label])=>{const ArtIcon=Icon as typeof Music2;return <div key={String(title)}><ArtIcon size={26}/><h3>{String(title)}</h3><p>{String(label)}</p></div>})}</div></div>;}
export default function PublicApp({path}:{path:string}){const pages:Record<string,React.ReactNode>={'/':<Home/>,'/scores':<Scores/>,'/events':<Events/>,'/results':<Results/>,'/gallery':<Gallery/>,'/about':<About/>};return <><Navbar path={path}/><main id="main" tabIndex={-1}>{pages[path]||<div className="page-container"><PageHeading kicker="PAGE NOT FOUND" title="A different stage awaits." description="This page is not part of the festival."/><Link className="button primary" href="/">Back to the festival<ArrowRight size={18}/></Link></div>}</main><Footer/></>;}

