import {useEffect,useRef,useState,type ReactNode} from 'react';import {ArrowUpRight,Menu,Trophy,Image as ImageIcon,CalendarDays,Music2,Search,RefreshCw,ArrowRight} from 'lucide-react';import Link from '@/lib/link';
import {Sheet,SheetContent,SheetTitle,SheetTrigger,SheetDescription} from '@/components/ui/sheet';import {Empty,EmptyHeader,EmptyMedia,EmptyTitle,EmptyDescription} from '@/components/ui/empty';import {Skeleton} from '@/components/ui/skeleton';import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';import {isConnected} from '@/services/config';
export const nav=[['Home','/'],['Live scores','/scores'],['Events','/events'],['Results','/results'],['Gallery','/gallery'],['About','/about']];
export function Brand(){return <Link href="/" className="brand"><span className="brand-mark">y.</span><span>YEBETH<span className="brand-year">2k26</span><small>GHS BEENCHI</small></span></Link>;}
export function Navbar({path}:{path:string}){const [open,setOpen]=useState(false);const [scrolled,setScrolled]=useState(false);useEffect(()=>{const fn=()=>setScrolled(window.scrollY>20);window.addEventListener('scroll',fn,{passive:true});return()=>window.removeEventListener('scroll',fn)},[]);useEffect(()=>setOpen(false),[path]);return <><a className="skip-link" href="#main">Skip to content</a><header className={'site-nav '+(scrolled?'scrolled':'')}><Brand/><nav aria-label="Main navigation">{nav.map(([name,url])=><Link href={url} key={url} className={path===url?'active':''} aria-current={path===url?'page':undefined}>{name}</Link>)}</nav><Sheet open={open} onOpenChange={setOpen}><SheetTrigger asChild><button className="icon-button mobile-menu" aria-label="Open navigation"><Menu size={23}/></button></SheetTrigger><SheetContent className="mobile-sheet"><SheetTitle>YEBETH2k26</SheetTitle><SheetDescription>Explore the festival.</SheetDescription><nav aria-label="Mobile navigation">{nav.map(([name,url])=><Link href={url} key={url} aria-current={path===url?'page':undefined}>{name}<ArrowUpRight size={18}/></Link>)}</nav></SheetContent></Sheet></header></>;}
export function Footer(){return <footer className="footer"><Link href="/">YEBETH2k26<small>GHS BEENCHI</small></Link><p>A celebration of expression. A community of talent.</p><nav aria-label="Footer navigation"><Link href="/about">About the festival</Link></nav><span>ARTS FESTIVAL 2026</span></footer>;}
export function Heading({kicker,title,description,action}:{kicker:string;title:string;description?:string;action?:ReactNode}){return <div className="section-heading"><div><p className="eyebrow ink">{kicker}</p><h2>{title}</h2>{description&&<p className="section-description">{description}</p>}</div>{action}</div>;}
export function PageHeading({kicker,title,description,children}:{kicker:string;title:string;description:string;children?:ReactNode}){return <div className="page-heading"><p className="eyebrow ink">{kicker}</p><div className="page-heading-row"><h1>{title}</h1>{children}</div><p>{description}</p></div>;}
export function TextLink({href,children}:{href:string;children:ReactNode}){return <Link className="text-link" href={href}>{children}<ArrowUpRight size={18}/></Link>;}
export function State({kind='events',loading=false,error=false,onRetry,title,description}:{kind?:string;loading?:boolean;error?:boolean;onRetry?:()=>void;title?:string;description?:string}){
 const Icon=kind==='gallery'?ImageIcon:kind==='scores'||kind==='results'?Trophy:CalendarDays;
 if(loading)return <div className="skeleton-grid" aria-label="Loading festival information" aria-busy="true">{[0,1,2].map(v=><div className="skeleton-card" key={v}><Skeleton className="h-10 w-10 rounded-xl"/><Skeleton className="h-5 w-2/3 mt-5"/><Skeleton className="h-4 w-full mt-3"/></div>)}</div>;
 return <Empty className="empty-state"><EmptyHeader><EmptyMedia variant="icon"><Icon/></EmptyMedia><EmptyTitle>{error?'A little pause in the programme.':title||({scores:'The stage is set.',results:'The best is yet to be announced.',gallery:'Great moments are on their way.',events:'The programme is taking shape.'}[kind]||'Nothing here yet.')}</EmptyTitle><EmptyDescription>{error?'We couldn’t load this information. Please try again.':description||({scores:'House standings will appear here when scores are published.',results:'No results have been published yet. Check back for the first winners.',gallery:'No moments have been uploaded yet. Festival photographs will appear here.',events:'No events are available yet. The festival schedule will appear here.'}[kind])}</EmptyDescription></EmptyHeader>{error?<button className="button secondary" onClick={onRetry}><RefreshCw size={16}/>Try again</button>:<span className="status-pill">{isConnected()?'MORE TO COME':'AWAITING FESTIVAL UPDATES'}</span>}</Empty>;
}
export function LiveBadge({connected,error,refreshing,updatedAt}:{connected:boolean;error?:boolean;refreshing?:boolean;updatedAt?:Date}){return <div className={'live-status '+(connected&&!error?'online':'')} role="status"><i/><span>{!connected?'Awaiting scores':error?'Updates paused':refreshing?'Updating scores…':'Live updates'}</span>{updatedAt&&!error&&<small>Updated {updatedAt.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small>}</div>;}
export function FieldSelect({label,value,onChange,options,placeholder='Select an option',required=false}:{label:string;value:string;onChange:(value:string)=>void;options:{value:string;label:string}[];placeholder?:string;required?:boolean}){return <label className="field"><span>{label}{required?' *':''}</span><Select value={value} onValueChange={onChange} required={required}><SelectTrigger className="filter-select" aria-label={label}><SelectValue placeholder={placeholder}/></SelectTrigger><SelectContent>{options.map(o=><SelectItem value={o.value} key={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></label>;}
export function SearchBox({value,onChange,label='Search'}:{value:string;onChange:(v:string)=>void;label?:string}){return <label className="search-box"><Search size={17}/><input aria-label={label} placeholder={label} value={value} onChange={e=>onChange(e.target.value)}/></label>;}
export function Count({value}:{value:number}){const [shown,setShown]=useState(value);const previous=useRef(value);useEffect(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){setShown(value);previous.current=value;return;}const from=previous.current;let start=0;let frame:number;function run(t:number){if(!start)start=t;const p=Math.min(1,(t-start)/550);setShown(p===1?value:Math.round((from+(value-from)*(1-Math.pow(1-p,3)))*100)/100);if(p<1)frame=requestAnimationFrame(run);}frame=requestAnimationFrame(run);previous.current=value;return()=>cancelAnimationFrame(frame)},[value]);return <>{shown.toLocaleString()}</>;}
export const formatDate=(value:string)=>{const d=new Date(value);return Number.isNaN(d.getTime())?'Date to be announced':d.toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})};
export const categories=['Dance','Music','Drama','Painting','Drawing','Photography','Literary','Instrumental Music','Recitation','Quiz','Ceremony','Other'];
export function FilterPills({value,onChange,values}:{value:string;onChange:(v:string)=>void;values:string[]}){return <div className="filter-pills" role="group" aria-label="Filter by category">{['All',...values].map(v=><button aria-pressed={value===v} className={value===v?'selected':''} key={v} onClick={()=>onChange(v)}>{v}</button>)}</div>;}
export function LoadMore({next,loading,onNext}:{next?:string|null;loading:boolean;onNext:()=>void}){return next?<div className="load-more"><button className="button secondary" onClick={onNext} disabled={loading}>{loading?'Loading…':'Load more'}<ArrowRight size={16}/></button></div>:null;}

